name: "ci build mysql"

on:
  pull_request:
  push:
    branches:
      - "master"

env:
  CI_DB_ENGINE: "mysql"

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['7.4', '8.0']
    steps:
      - name: Setup PHP Action
        uses: shivammathur/setup-php@1.8.2
        with:
          extensions: intl
          php-version: "${{ matrix.php-versions }}"
          coverage: xdebug
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      - name: Setup MySQL
        uses: samin/mysql-action@v1.3
        with:
          mysql version: 5.7
          mysql password: test
          mysql user: test
          mysql database: mezzio
      - name: Checkout
        uses: actions/checkout@v2
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"
      - name: "Install dependencies"
        run: "composer install --prefer-dist --no-progress --no-suggest && composer development-enable"
      - name: "Code analyze"
        run: "composer analyze"
      - name: "CS Check"
        run: "composer cs-check"
      - name: "Setup Test and DB Config"
        run: "cp config/autoload/local.php.ci.${{ env.CI_DB_ENGINE }}.dist config/autoload/local.php"
      - name: "Run test suite"
        run: "composer test-coverage"
      - if: matrix.php-versions == '7.4'
        name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: tests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true